config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'posts#feed'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, only: %i[show], shallow: true do
    resources :posts, except: %i[index], shallow: true do
      resources :likes, only: %i[create destroy]
      resources :comments, except: %i[index new show]
    end
    resources :stories, except: %i[index]
    member do
      post :follow, controller: :follows
      post :unfollow, controller: :follows
      post :accept_follow, controller: :follows
    end
    collection do
      get :search
    end
  end
  resources :requests, only: %i[index destroy]
  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index]
      resources :posts, only: %i[index]
      resources :stories, only: %i[index]
    end
  end
  get '*path', to: 'application#route_not_found'
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: true, length: { maximum: 100 }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_post, only: %i[create]
  before_action :set_comment, only: %i[edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def create
    @comment = @post.comments.new(content: params[:content])

    @comment.user_id = current_user.id
    authorize @comment

    flash[:alert] = @comment.errors.full_messages unless @comment.save
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Comment updated successfully.'
    else
      flash[:alert] = @comment.errors.full_messages
    end

    redirect_to post_path(@comment.post)
  end

  def destroy
    flash[:alert] = @comment.errors.full_messages unless @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def authorize_user
    authorize @comment
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_new.html.erb
<%= form_with model: @comment, url: post_comments_path(@post), class: "form-inline" do |f| %>
  <div class="form-group">
    <%= f.text_field :content, placeholder: "Make a comment", required: true, class: 'form-control', id: "inp" %>
  </div>
  <div class="form-group">
    <%= f.submit "Add", remote: true, class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/comments/_post_comments.html.erb
<div id="delete<%= comment.id %>">
  <b><%= comment.user.username %></b>
  <%= comment.content %>
  <% if policy(comment).edit? %>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment_path(comment), remote: true, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %><br>
</div>

app/views/comments/create.js.erb
$("#comment").prepend("<%= escape_javascript(render '/comments/post_comments', comment: @comment) %>");
$("#inp").val('');

app/views/comments/destroy.js.erb
$("#delete<%= @comment.id %>").remove();

app/views/comments/edit.html.erb
<br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-7">
      <h2>Edit Your Comment</h2><br>
      <%= form_with model: @comment do |f| %>
        <div class="form-group row">
          <%= f.label :comment, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-7">
            <%= f.text_field :content, required: true, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-2">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Edit Your Comment", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>