config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'posts#feed'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, only: %i[show], shallow: true do
    resources :posts, except: %i[index], shallow: true do
      resources :likes, only: %i[create destroy]
      resources :comments, except: %i[index new show]
    end
    resources :stories, except: %i[index]
    member do
      post :follow, controller: :follows
      post :unfollow, controller: :follows
      post :accept_follow, controller: :follows
    end
    collection do
      get :search
    end
  end
  resources :requests, only: %i[index destroy]
  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index]
      resources :posts, only: %i[index]
      resources :stories, only: %i[index]
    end
  end
  get '*path', to: 'application#route_not_found'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_many :followers, foreign_key: :following_id, class_name: 'Follow', dependent: :restrict_with_exception,
                       inverse_of: false
  has_many :followings, foreign_key: :follower_id, class_name: 'Follow', dependent: :restrict_with_exception,
                        inverse_of: false

  validates :username, presence: true, uniqueness: true, length: { minimum: 2, maximum: 15 }
  validates :name, length: { maximum: 30 }
  validates :bio, length: { maximum: 50 }
  validates :image, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class UsersController < ApplicationController
      skip_before_action :authenticate_user!

      def index
        render json: User.all.with_attached_image
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def search
    @users = User.ransack(username_cont: params[:q]).result

    respond_to do |format|
      format.html {}
      format.json { @users = @users.limit(10) }
    end
  end

  def show
    @user = User.find(params[:id])
    @request = Request.find_by(following_id: @user.id, follower_id: current_user.id)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end

  def requested(current_user_id, followed_user_id)
    Request.find_by(following_id: followed_user_id, follower_id: current_user_id)
  end

  def post(user)
    checker = user.posts.find { |post| post.user_id == user.id }
    return true if checker
  end

  def story(user)
    checker = user.stories.find { |story| story.user_id == user.id }
    return true if checker
  end

  def private_profile(user)
    user.status
  end
end

app/views/users/route_not_found.html.erb
<br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-7">
      <h2>You are on wrong route</h2><br>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Users</th>
      <th>Visit This user</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Visit', user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="profile">
      <div class="col-md-4">
        <div class="profile-image">
          <% if @user.image.attached? %>
            <%= cl_image_tag(@user.image.key) %>
          <% else %>
            <%= image_tag("https://thumbs.dreamstime.com/b/default-avatar-profile-icon-social-media-user-vector-default-avatar-profile-icon-social-media-user-vector-portrait-176194876.jpg") %>
          <%end%>
        </div>
      </div>
      <div class="col-md-8">
        <h2 class="profile-user-name"><%= @user.username %></h2>
        <% if policy(@user).show? %>
          <%= link_to 'New Post', new_user_post_path(@user), class: "btn follow-btn" %>
          <%= link_to 'New Story', new_user_story_path(@user), class: "btn follow-btn" %>
          <%= link_to '<i class="glyphicon glyphicon-cog"></i>'.html_safe, edit_user_registration_path, class: "btn follow-btn" %>
        <% else %>
          <% if requested(current_user.id, @user.id) %>
            <%= link_to 'Requested', request_path(@request.id), method: :delete, class: "btn follow-btn" %>
          <% elsif following(current_user.id, @user.id) %>
            <%= link_to 'unfollow', unfollow_user_path(@user), method: :post, class: "btn follow-btn" %>
          <% else %>
            <%= link_to 'follow', follow_user_path(@user), method: :post, class: "btn follow-btn" %>
          <% end %>
        <% end %>
        <div class="profile-stats">
            <span class="profile-stat-count"><%= @user.posts.count %></span> posts
            <span class="profile-stat-count"><%= @user.followers.count %></span> followers
            <span class="profile-stat-count"><%= @user.followings.count %></span> following
        </div>
        <div class="profile-bio">
          <p><span class="profile-real-name"><%= @user.name %></span> <%= @user.bio %></p>
        </div>
      </div>
    </div>
  </div>
</div><br>
<% if post(@user) || story(@user) %>
  <% if policy(@user).show? %>
    <%= render partial: '/stories/single_story', collection: @user.stories, as: :story %>
    <br><br><br><br><br><br><br>
    <%= render partial: '/posts/profile_post', collection: @user.posts, as: :post %>
  <% elsif !following(current_user.id, @user.id) && @user.status? %>
    <br><br><br><h1 class="text-center">This is a private Profile</h1>
  <% else %>
    <%= render partial: '/stories/single_story', collection: @user.stories, as: :story %>
    <br><br><br><br><br><br><br>
    <%= render partial: '/posts/profile_post', collection: @user.posts, as: :post %>
  <% end %>
<% else %>
  <br><br><br><h1 class="text-center">No Posts And Stories Yet</h1>
<% end %>