config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'posts#feed'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, only: %i[show], shallow: true do
    resources :posts, except: %i[index], shallow: true do
      resources :likes, only: %i[create destroy]
      resources :comments, except: %i[index new show]
    end
    resources :stories, except: %i[index]
    member do
      post :follow, controller: :follows
      post :unfollow, controller: :follows
      post :accept_follow, controller: :follows
    end
    collection do
      get :search
    end
  end
  resources :requests, only: %i[index destroy]
  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index]
      resources :posts, only: %i[index]
      resources :stories, only: %i[index]
    end
  end
  get '*path', to: 'application#route_not_found'
end

app/models/story.rb
# frozen_string_literal: true

class Story < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/controllers/api/v1/stories_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class StoriesController < ApplicationController
      skip_before_action :authenticate_user!

      def index
        render json: Story.all.with_attached_image
      end
    end
  end
end

app/controllers/stories_controller.rb
# frozen_string_literal: true

class StoriesController < ApplicationController
  before_action :set_user, only: %i[new create]
  before_action :set_story, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[show edit update destroy]

  def new
    @story = @user.stories.new
    authorize @story
  end

  def create
    @story = @user.stories.new(story_params)
    authorize @story

    if @story.save
      create_job_for_deleting
      flash[:notice] = 'Story created successfully.'
    else
      flash[:alert] = @story.errors.full_messages
    end

    redirect_to user_path(params[:user_id])
  end

  def show; end

  def edit; end

  def update
    if @story.update(story_params)
      flash[:notice] = 'Story updated successfully.'
    else
      flash[:alert] = @story.errors.full_messages
    end

    redirect_to @story
  end

  def destroy
    remove_job_from_queue
    if @story.destroy
      flash[:notice] = 'Story deleted successfully.'
    else
      flash[:error] = @story.errors.full_messages
    end

    redirect_to user_path current_user
  end

  private

  def story_params
    params.require(:story).permit(:image)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_story
    @story = Story.find(params[:id])
  end

  def create_job_for_deleting
    @story.job_id = DeleteStoryJob.set(wait: 24.hours).perform_later(@story).provider_job_id
    @story.save
  end

  def remove_job_from_queue
    queue = Sidekiq::ScheduledSet.new
    queue.each do |job|
      job.delete if job.jid == @story.job_id
    end
  end

  def authorize_user
    authorize @story
  end
end

app/helpers/stories_helper.rb
# frozen_string_literal: true

module StoriesHelper
end

app/views/stories/_single_story.html.erb
<div class="wrapper">
  <div class="story">
    <div class="story-wrapper">
      <%= link_to cl_image_tag(story.image.key), story_path(story) if story.image.attached? %>
    </div>
  </div>
</div>

app/views/stories/edit.html.erb
<br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-7">
      <h2>Edit Your Story</h2><br>
      <%= form_with model: @story do |f| %>
        <div class="form-group row">
          <%= f.label :image, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-7">
            <%= f.file_field :image, required: true, accept: 'image/png, image/jpg, image/jpeg', class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-2">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Update Story", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stories/new.html.erb
<br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-7">
      <h2>Create New Story</h2><br>
      <%= form_with model: @story, url: user_stories_path do |f| %>
        <div class="form-group row">
          <%= f.label :image, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-7">
            <%= f.file_field :image, required: true, accept: 'image/png, image/jpg, image/jpeg', class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-2">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Create New Story", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stories/show.html.erb
<div class="container">
  <div class="row">
    <div class="post-show">
      <div class="post-wrapper">
        <br><%= link_to "#{@story.user.username}", user_path(@story.user), class: "username" %><br><br>
        <%= cl_image_tag @story.image.key %>
        <% if policy(@story).edit? %>
         <br><%= link_to 'Edit Story', edit_story_path(@story), class: "btn follow-btn" %>
          <br><%= link_to 'Delete This Story', story_path(@story), class: "btn follow-btn", method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  </div>
</div>