config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'posts#feed'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, only: %i[show], shallow: true do
    resources :posts, except: %i[index], shallow: true do
      resources :likes, only: %i[create destroy]
      resources :comments, except: %i[index new show]
    end
    resources :stories, except: %i[index]
    member do
      post :follow, controller: :follows
      post :unfollow, controller: :follows
      post :accept_follow, controller: :follows
    end
    collection do
      get :search
    end
  end
  resources :requests, only: %i[index destroy]
  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index]
      resources :posts, only: %i[index]
      resources :stories, only: %i[index]
    end
  end
  get '*path', to: 'application#route_not_found'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :images, attached: true, limit: { min: 1, max: 10 }, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates :caption, length: { maximum: 150 }
end

app/controllers/api/v1/posts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PostsController < ApplicationController
      skip_before_action :authenticate_user!

      def index
        render json: Post.all.with_attached_images
      end
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_user, only: %i[new create]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[show edit update destroy]

  def feed
    @followings = current_user.followings
  end

  def new
    @post = @user.posts.new
    authorize @post
  end

  def create
    @post = @user.posts.new(post_params)
    authorize @post

    if @post.save
      flash[:notice] = 'Post created successfully.'
    else
      flash[:alert] = @post.errors.full_messages
    end
    redirect_to user_path(current_user)
  end

  def show
    @images = @post.images.page(params[:page]).per(1)
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post updated successfully.'
      redirect_to @post
    else
      flash[:alert] = @post.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = 'Post deleted successfully.'
    else
      flash[:alert] = @post.errors.full_messages
    end
    redirect_to user_path current_user
  end

  private

  def post_params
    params.require(:post).permit(:caption, images: [])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def authorize_user
    authorize @post
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_feed_post.html.erb
<br>
<div class="container">
  <div class="feed-post">
    <div class="row">
      <div class="col-md-1">
        <div class="post-profile-wrapper">
          <br>
          <% if post.user.image.attached? %>
            <%= link_to cl_image_tag(post.user.image.key), user_path(post.user) %>
          <% else %>
            <%= image_tag("https://thumbs.dreamstime.com/b/default-avatar-profile-icon-social-media-user-vector-default-avatar-profile-icon-social-media-user-vector-portrait-176194876.jpg") %>
          <%end%>
        </div>
      </div>
      <div class="col-md-1">
        <br><br><%= link_to "#{post.user.username}", user_path(post.user), class: "username" %>
      </div>
    </div><br>
    <div class="row">
      <div class="col-md-8">
        <div class="post-wrapper">
          <%= link_to cl_image_tag(post.images.first.key), post_path(post) if post.images.attached? %>
        </div>
      </div>
    </div>
  </div>
</div><br>

app/views/posts/_profile_post.html.erb
<div class="single-post">
	<div class="post-item">
		<div class="post-item-info">
			<span><%= post.likes.count %></span><i class="fas fa-heart"></i>
			<span><%= post.comments.count %></span><i class="fas fa-comment"></i>
		</div>
		<%= link_to cl_image_tag(post.images.first.key), post_path(post) if post.images.attached? %>
	</div>
</div>

app/views/posts/_single_post.html.erb
<div class="single-post">
  <div class="post-wrapper">
  	<div class="post-item">
	    <div class="post-item-info">
				<span><%= post.likes.count %></span><i class="fas fa-heart"></i>
				<span><%= post.comments.count %></span><i class="fas fa-comment"></i>
			</div>
			<%= link_to image_tag(post.images.first), post_path(post) if post.images.attached? %>
  	</div>
  </div>
</div>

app/views/posts/edit.html.erb
<br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-7">
      <h2>Edit Your Post</h2><br>
      <%= form_with model: @post do |f| %>
        <div class="form-group row">
          <%= f.label :caption, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-7">
            <%= f.text_field :caption, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-2">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Update Your Post", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/feed.html.erb
<% @followings.each do |user| %> 
  <% @user = User.find(user.following_id) %>
  <%= render partial: '/posts/feed_post', collection: @user.posts, as: :post %>
<%end%>

app/views/posts/index.html.erb
<% @followings.each do |user| %> 
  <% @user = User.find(user.following_id) %>
  <%= render partial: '/posts/feed_post', collection: @user.posts, as: :post %>
<%end%>

app/views/posts/new.html.erb
<br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-7">
      <h2>Create New Post</h2><br>
      <%= form_with model: @post, url: user_posts_path do |f| %>

        <div class="form-group row">
          <%= f.label :caption, class: 'col-md-2 form-label' %>
          <div class="col-md-7">
            <%= f.text_field :caption, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :Images, class: 'col-sm-2 form-label' %>
          <div class="col-sm-7">
            <%= f.file_field :images, multiple: true, required: true, direct_upload: true, accept: 'image/png, image/jpg, image/jpeg', class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-2">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Create New Post", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<br><br><br>
<div class="container">
  <div class="row">
    <div class="post-show img img-thumbnail">
      <div class="col-md-8">
        <div class="post-wrapper">
          <% @images.each do |image| %>
            <%= cl_image_tag(image.key) %>
          <% end %>
          <%= paginate @images %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="row">
          <div class="col-md-2">
            <div class="post-profile-wrapper">
              <% if @post.user.image.attached? %>
                <br><%= link_to cl_image_tag(@post.user.image.key), user_path(current_user) %>
              <% else %>
                <br><%= image_tag("https://thumbs.dreamstime.com/b/default-avatar-profile-icon-social-media-user-vector-default-avatar-profile-icon-social-media-user-vector-portrait-176194876.jpg") %>
              <%end%>
            </div>
          </div>
          <div class="col-md-10">
            <br><br><%= link_to "#{@post.user.username}", user_path(@post.user), class: "username" %>
            <% if policy(@post).show? %>
              <%= link_to '<i class="glyphicon glyphicon-cog"></i>'.html_safe, edit_post_path(@post), class: "btn" %>
              <%= link_to '<i class="glyphicon glyphicon-remove"></i>'.html_safe, post_path(@post), class: "btn", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
        <hr>
        <div class="row caption">
          <%= @post.caption %>
        </div>
        <hr>
        <div class="likes-comments">
          <%= render '/likes/like' %>
          <%= render '/comments/new' %><br>
          <div id="comment">
            <%= render partial: '/comments/post_comments', collection: @post.comments.order("created_at DESC"), as: :comment %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>